name: triptracker_flutter
description: IRSHAD HIGH SCHOOL Trip Tracker - minimal scaffold
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  google_fonts: ^4.0.3
  # Stubs for later
  geolocator: ^9.0.2
  battery_plus: ^4.0.0
  flutter_map: ^3.0.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
